---

image: python:3.7.3


definitions:
  steps:
    - step: &test-security
        name: Test security
        caches:
          - pip
        script:
          - pip install safety
          - safety check

    - step: &test-the-code
        name: Test the code
        caches:
          - pip
          - precommit
        script:
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - gitlint --config .tests/.gitlint
          - pre-commit install -f
          - pre-commit run --all-files
  caches:
    precommit: ~/.cache/pre-commit


pipelines:
  default:
    - parallel:
        - step: *test-security
        - step: *test-the-code
