---

- name: '(smoke-test) -- check if credentials are valid'
  uri:
    url: '{{ inventory__elastic_use_ssl | ternary("https://", "http://", omit) }}{{ ansible_hostname }}:{{ inventory__elasticsearch_endpoint_port }}'
    user: '{{ vault__elastic_username }}'
    password: '{{ vault__elastic_password }}'
  register: 'result'
  until: 'result is success'
  retries: '10'
  delay: '5'
