---

- name: 'start service -- {{ sshd__service }}'
  systemd:
    name: '{{ sshd__service }}'
    state: 'started'


- name: 'template -- {{ sshd__config_dest }}'
  template:
    src: '{{ sshd__config_src }}'
    dest: '/etc/ssh/sshd_config'
    owner: 'root'
    group: 'root'
    mode: '0600'
    force: 'yes'
    validate: '/usr/sbin/sshd -T -f %s'
  notify: 'restart service -- {{ sshd__service }}'


- name: 'copy banner -- {{ sshd__banner_dest }}'
  copy:
    src: '{{ sshd__banner_src }}'
    dest: '/etc/ssh/banner'
    owner: 'root'
    group: 'root'
    mode: '0400'
    force: 'yes'
    validate: 'ls %s'
  notify: 'restart service -- {{ sshd__service }}'
