---

- name: 'start service -- {{ sshd__service }}'
  systemd:
    state: 'started'
    name: '{{ sshd__service }}'


- name: 'template -- {{ sshd__config_dest }}'
  template:
    src: '{{ sshd__config_src }}'
    dest: '{{ sshd__config_dest }}'
    owner: '{{ sshd__config_owner }}'
    group: '{{ sshd__config_group }}'
    mode: '{{ sshd__config_mode }}'
    validate: '{{ sshd__config_validate }}'
    force: '{{ sshd__config_force }}'


- name: 'copy banner -- {{ sshd__banner_dest }}'
  copy:
    src: '{{ sshd__banner_src }}'
    dest: '{{ sshd__banner_dest }}'
    owner: '{{ sshd__banner_owner }}'
    group: '{{ sshd__banner_group }}'
    mode: '{{ sshd__banner_mode }}'
    validate: '{{ sshd__banner_validate }}'
    force: '{{ sshd__banner_force }}'
  notify: 'restart service -- {{ sshd__service }}'
