---

- name: 'start service -- {{ docker__service }}'
  systemd:
    name: '{{ docker__service }}'
    state: 'started'


- name: 'template -- {{ docker__config_src }} to {{ docker__config_dest }}'
  template:
    src: '{{ docker__config_src }}'
    dest: '{{ docker__config_dest }}'
    owner: 'root'
    group: 'root'
    mode: '0400'
    validate: 'ls %s'
    force: 'yes'
  notify:
    - 'restart service -- {{ docker__service }}'
