---

- name: 'start service -- {{ docker__service }}'
  systemd:
    name: '{{ docker__service }}'
    state: 'started'


- name: 'template -- {{ docker__config_src }} to {{ docker__config_dest }}'
  template:
    src: '{{ docker__config_src }}'
    dest: '{{ docker__config_dest }}'
    owner: '{{ docker__config_owner }}'
    group: '{{ docker__config_group }}'
    mode: '{{ docker__config_mode }}'
    validate: '{{ docker__config_validate }}'
    force: '{{ docker__config_force }}'
  notify:
    - 'restart service -- {{ docker__service }}'
