---

- name: 'get ownca root CA certificate to provided target path'
  copy:
    src: '{{ kibana__ca_cert_source }}'
    remote_src: '{{ kibana__get_ssl_from_guest }}'
    dest: '{{ kibana__ca_cert_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ kibana__service }}'


- name: 'get ownca private key to provided target path'
  copy:
    src: '{{ kibana__key_source }}'
    remote_src: '{{ kibana__get_ssl_from_guest }}'
    dest: '{{ kibana__key_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ kibana__service }}'


- name: 'get ownca ssl certificate to provided target path'
  copy:
    src: '{{ kibana__cert_source }}'
    remote_src: '{{ kibana__get_ssl_from_guest }}'
    dest: '{{ kibana__cert_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ kibana__service }}'


- name: 'deploy configuration file -- /etc/kibana/kibana.yml'
  template:
    src: 'kibana.yml.j2'
    dest: '/etc/kibana/kibana.yml'
    mode: '0644'
  notify:
    - 'restart -- {{ kibana__service }}'
    - '(smoke-test) -- check if service is reachable'
