---

- name: 'get ownca root CA certificate to provided target path'
  copy:
    src: '{{ elastic_7__ca_cert_source }}'
    remote_src: '{{ elastic_7__get_ssl_from_guest }}'
    dest: '{{ elastic_7__ca_cert_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ elastic_7__service }}'


- name: 'get ownca private key to provided target path'
  copy:
    src: '{{ elastic_7__key_source }}'
    remote_src: '{{ elastic_7__get_ssl_from_guest }}'
    dest: '{{ elastic_7__key_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ elastic_7__service }}'


- name: 'get ownca ssl certificate to provided target path'
  copy:
    src: '{{ elastic_7__cert_source }}'
    remote_src: '{{ elastic_7__get_ssl_from_guest }}'
    dest: '{{ elastic_7__cert_target }}'
    owner: 'root'
    group: 'root'
    mode: 'preserve'
  notify: 'restart -- {{ elastic_7__service }}'


- name: 'deploy configuration file -- /etc/elasticsearch/elasticsearch.yml'
  template:
    src: 'elasticsearch.yml.j2'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    mode: '0440'
  notify: 'restart -- {{ elastic_7__service }}'


- name: 'start -- {{ elastic_7__service }}'
  systemd:
    name: '{{ elastic_7__service }}'
    state: 'started'
    enabled: 'yes'
  notify: '(smoke-test) -- check master-master communication'
