---

- name: 'install -- docker-compose'
  delegate_to: 'localhost'
  become: 'no'
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose__version }}/docker-compose-Linux-x86_64'
    dest: '{{ inventory_dir }}/files/docker-compose'
    mode: 0755


- name: 'send the binary to hosts -- {{ docker_compose__path }}'
  copy:
    src: '{{ inventory_dir }}/files/docker-compose'
    dest: '{{ docker_compose__path }}'
    owner: '{{ docker_compose__owner }}'
    group: '{{ docker_compose__group }}'
    mode: '{{ docker_compose__mode }}'
