---

- name: 'install -- docker-compose'
  delegate_to: 'localhost'
  become: 'no'
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose__version }}/docker-compose-Linux-x86_64'
    dest: '{{ inventory_dir }}/files/docker-compose'
    mode: '0755'


- name: 'send the binary to hosts -- /usr/local/bin/docker-compose'
  copy:
    src: '{{ inventory_dir }}/files/docker-compose'
    dest: '/usr/local/bin/docker-compose'
    owner: 'root'
    group: 'root'
    mode: '0755'
